### ISSUE TITLE
Typescript errors with 4.1.1

### ISSUE THREAD

**Issue by tsiivola** [froala/wysiwyg-editor#4667]
##### Expected behavior.
My custom plugin works without errors from typescript compiler. 

##### Actual behavior.
I get typescript errors from custom plugin code. The code used to work without errors with 4.0.10

##### Steps to reproduce the problem.
This simple plugin gives me errors. Firstly the 'this' of the callback function is not a Froala editor type, and the saveStep and setAfter functions expect an additional argument. 
```typescript
FroalaEditor.RegisterCommand('testCase', {
    callback() {
        this.undo.saveStep();
        this.selection.setAfter('abc');
    },
});
```

Here are some changes to the index.d.ts file that fix all the errors that I happened to encounter. 
```diff
@@ -181,7 +181,7 @@
 
       // Called when the button is hit.
       // The current context is the editor instance.
-      callback: (buttonName: string, val?: any, params?: any) => void;
+      callback: (this: FroalaEditor, buttonName: string, val?: any, params?: any) => void;
 
       // Called when the button state might have changed.
       refresh: (button: any) => void;
@@ -1819,10 +1819,10 @@
     ranges(index: number): Range | Range[];
     restore(): boolean;
     save(): void;
-    setAfter(node: Element, use_current_node: any): boolean;
-    setAtEnd(node: Element, deep: any): boolean;
-    setAtStart(node: Element, deep: any): boolean;
-    setBefore(node: Element, use_current_node: any): boolean;
+    setAfter(node: Element, use_current_node?: boolean): boolean;
+    setAtEnd(node: Element, deep?: boolean): boolean;
+    setAtStart(node: Element, deep?: boolean): boolean;
+    setBefore(node: Element, use_current_node?: boolean): boolean;
     text(): string;
     remove(): boolean;
     rangeElement(rangeContainer: any, offset: any) : any;
@@ -1895,7 +1895,7 @@
     canDo(): boolean;
     canRedo(): boolean;
     reset(): object;
-    saveStep(snapshot : any): void;
+    saveStep(snapshot?: any): void;
     _init(): void;
     run(): void;
     redo(): void;

```

**Comment by rostyslav-horytskyi** [comment]
Faced the same problem. In addition to this, I get the following errors:

- `Property 'el' does not exist on type 'FroalaEditor'.`
- RegisterCommand -> callback -> `Argument of type 'Partial<RegisterCommandParameters>' is not assignable to parameter of type 'FroalaEditor'.`
- `Property '$box' does not exist on type 'FroalaEditor'.`
- `Property '$wp' does not exist on type 'FroalaEditor'.`

**Comment by 4kochi** [comment]
Hello,

we have the same problem with the TypeScript error.


```
editor.undo.saveStep()

// Expected 1 arguments, but got 0.ts(2554)
// index.d.ts(1898, 14): An argument for 'snapshot' was not provided.
```

If the change is intended the it would be nice if the documentation is updated so that we adopt our code accordingly. Otherwise an update of the index.d.ts would be appreciated.

Thank you

**Comment by fexxdev** [comment]
Yeah we have issues in our end too
![image](https://github.com/froala/wysiwyg-editor/assets/26311786/f2fa4112-cd04-4484-838b-673e56254dfc)

Working with 4.1.0
angular 16

**Comment by D4sK43nguru** [comment]
I have the same problems with other functions too. Though, I have to say that I am working on a rather big project that I was assigned too after a colleague left the company. Thus I don't necessarily know, if some of these functions and properties are custom defined and can't be found in the docs because of that or if they are just not defined in the documentation.

Not defined in the `index.d.ts` are 
```JS
editor.commands.exec()
editor.customToolbars
editor.externalWrapper
editor.formatCleared
editor.link.dropdown
editor.screenSize
editor.selectionColors
editor.table.focused
editor.table.parentCell
editor.table.selectedCellsList // The editor.table parameters are listed in your documentation, 
                               // but not all in the index.d.ts
```

and I found the following functions being either typed incompletely or wrongly (mismatching with the documentation on the webpage)
```JS
editor.format.is()             // Having both parameters being necessary seems wrong, 
                               // since the parameter names suggest that you can 
                               // check for both a tagName and an attribute separately
editor.image.get()
editor.selection.blocks()      // index.d.ts expects a parameter for the function,  
                               // the online documentation doesn't
editor.selection.get()         // This function is typed to return a string. 
                               // But accessing Selection.prototype properties like 
                               // Selection.anchorNode works too
```

Apart from that, all properties from the FroalaConfig interface are marked as required, thus giving a warning when one is not implementing all ~200 properties.

I am currently working on
- froala-editor@4.1.1
- react@17.0.2

**Comment by tsiivola** [comment]
Version 4.1.2 fixes the errors that I have encountered, I will close this issue.
