### ISSUE TITLE
popups.setContainer() throws error if custom container is used

### ISSUE THREAD

**Issue by robinwassen** [froala/wysiwyg-editor#3750]
The documentation for [popups.setContainer (id, container)](https://www.froala.com/wysiwyg-editor/docs/methods#popups.setContainer) demonstrates that you can pass in $(document.body) as jQuery Object container to popups. If you do similar to the example and pass in $(document.body) as the container argument the function will throw an error.

This was working in 2.7.6, and is therefore a regression between that version and the current latest 3.0.6.

##### Expected behavior.
- The container should be able to set any jQuery Object as popup container

##### Actual behavior.
- The container throws an error that isVisible() is not a function on the container variable. isVisible() is not a standard JavaScript nor jQuery function.

##### Steps to reproduce the problem.

1. Open the JSFiddle: https://jsfiddle.net/8x7c05za/1/
2. Click on the "open" toolbar button
3. Check the error in the console

The example code is a copy paste of the [Custom Popup Concept - Complete Example](https://www.froala.com/wysiwyg-editor/docs/concepts/custom/popup) with the container argument as the only notable change.

##### Editor version.
3.0.6

##### OS.
macOS Catalina

##### Browser.
Chrome 78

##### Recording.
N/A

**Comment by shnigi** [comment]
Can confirm I have the same problem with 3.2.2. Trying to put new container ID for double modal use case and getting  t.isVisible is not a function error. Without container defined it will render the popup outside of my modal dialog which has focustrap and then buttons can't be pressed on that popup.

**Comment by ilyaskarim** [comment]
We’re closing this issue due to inactivity. If you’re still experiencing this problem on the latest version of our editor, please feel free to reopen the issue and let us know. You can find details on the latest updates here: [Froala Editor Changelog](https://froala.com/wysiwyg-editor/changelog/).
