### ISSUE TITLE
Property MARKERS does not exist after upgrading to 4.1.0 using typescript

### ISSUE THREAD

**Issue by goodpilotfish** [froala/wysiwyg-editor#4648]
##### Expected behavior.
**Expected behavior.**
The following code should pass a tsc check after upgrading to 4.1.0
```
import FroalaEditor from "froala-editor";

FroalaEditor.MARKERS
FroalaEditor.ENTER_BR
```

This worked well on 4.0.19 before [index.d.ts](https://github.com/froala/wysiwyg-editor/blame/master/index.d.ts) was introduced. Am I missing something?
Possible workaround is to disable the type checking using (FroalaEditor as any).ENTER_BR...but that feels wrong.

##### Actual behavior.
When running tsc:
```
error TS2339: Property 'ENTER_BR' does not exist on type 'typeof FroalaEditor'.
error TS2339: Property 'MARKERS' does not exist on type 'typeof FroalaEditor'.
```

##### Steps to reproduce the problem.
Use FroalaEditor.MARKERS or FroalaEditor.ENTER_BR in your code.

Package.json:
"froala-editor": "^4.1.0"

##### Editor version.
4.1.0 

##### OS.
Mac

##### Browser.
N/A

**Comment by goodpilotfish** [comment]
Awesome!
