### ISSUE TITLE
Froula Mention Feature

### ISSUE THREAD

**Issue by mrdevsufiyan** [froala/wysiwyg-editor#4924]
Hello,

i am using Froala editor and trying to implement @mention feature. i am using froala version v4.0.17 i used tribute.js for that but it creates problem if i pass fullPage: true. 

**Tribute.js**

`// Initialize Froala and attach Tribute on editor init
    new FroalaEditor('#editor', {
	fullPage : true,
      events: {
        initialized: function() {
          var editor = this;
          // Attach Tribute.js to the editable element
          tribute.attach(editor.el);
          // Prevent Enter from closing the list prematurely
          editor.events.on(
            'keydown',
            function(e) {
              if (e.which === FroalaEditor.KEYCODE.ENTER && tribute.isActive) {
                return false;
              }
            },
            true
          );
        }
      }
    });`

**At.js**

alternatively i tried to implement the feature using at.js library but it doesn't work in the froala v4.0.17. it is giving error of `atwho is not a function`

**Code** 
`new FroalaEditor('#editor', {
	fullPage : true,
      events: {
        initialized: function() {
          var editor = this;
          // Attach Tribute.js to the editable element
          tribute.attach(editor.el);
          // Prevent Enter from closing the list prematurely
          editor.events.on(
            'keydown',
            function(e) {
              if (e.which === FroalaEditor.KEYCODE.ENTER && tribute.isActive) {
                return false;
              }
            },
            true
          );
        }
      }
    });`

is there any best approach to implement @mention functionality in the froala with any version???
